### ISSUE TITLE
AVOID_USING_CFMODULE_TAG appears too often

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#145]
I have a `.cfm` file with the content:

    <cfinclude template="incl.cfm">
    <cfmodule template="incl.cfm">

I run `CFLint-0.6.1-all.jar -includeRule AVOID_USING_CFINCLUDE_TAG,AVOID_USING_CFINCUDE_TAG,AVOID_USING_CFMODULE_TAG` and receive one result: `Avoid using <cfmodule> tags.`
It seems test `AVOID_USING_CFINCLUDE_TAG`is only executed inside a component. That looks right to me. Why is the CFINCLUDE test executed without the check for component?

**Comment by justinmclean** [comment]
cfinclude can be use outside of components to good effect - think something like including the header or footer of a page. With the example above it seems to be OK to use cfmodule. Depending on your point of view perhaps better due to scoping. These days I can imagine that cfmodule would need to be used that often when you have cfimport and just use cf_xxxx or prefix:xxxx with cfimport.

**Comment by justinmclean** [comment]
Here's a couple of good discussions on it:
http://cfbestpractices.blogspot.com.au/2012/05/avoid-using-cfinclude-within-cfc.html
http://blog.adamcameron.me/2012/07/which-is-better-having-your-methods.html

**Comment by bardware** [comment]
I understand your point. Thanks for explaining.
