### ISSUE TITLE
Provide a roadmap

### ISSUE THREAD

**Issue by jevans-gp** [cflint/CFLint#154]
It'd be interesting to see a roadmap of what needs to be done to get to version 1?

**Comment by ryaneberly** [comment]
@jevans-gp 

Something like:

**Version 1.0.**
* Parameterize all the core plugins.  See commit: https://github.com/cflint/CFLint/commit/40e64a434e18af427a54a9ec1edb1e4cdf8a759b

* Clean up Documentation:
    * Quick start
    * How to configure / customize the rules
    * How to create a plugin

* #114 

Got other suggestions?

**Comment by jevans-gp** [comment]
I don't have suggestions, but i'd like to be able to help.

I'll take a look at Parameterisation, but i won't promise anything.

**Comment by ryaneberly** [comment]
I'm not is 'parameterization' is the correct term for it.  But instead of hardcoding the severity and the message text in code -- it is placed in the json configuration.

The resulting code is cleaner too.   Just add the message code and the rest is filled in by the framework.  If you review the changes made by the commit I mentioned, it should make some sense.

Just send out a PR if you want to try some.   Thanks.

**Comment by ryaneberly** [comment]
1.0.0-RC1 includes 
* correct parameterization of all plugins.  
* all plugins use the context framework.
* rule groups are implemented
* folder specific configuration support:  .cflintrc and .cflintrc.xml
