### ISSUE TITLE
java.lang.NoSuchMethodError: cfml.parsing.cfscript.CFFunctionExpression.getArgs()Ljava/util/Vector

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#292]
Hi,

sorry to bother, as I filed this over at the [CFEclipse](https://github.com/cfeclipse/cfeclipse/issues/83) repo some times ago. 
The topmost lines in the stacktrace stem from `com.cflint.CFLint` so I wonder if you might have an idea what the problem may be. I just scanned my code with CFLint.jar and got no severe exception. Is this a matter of the CFLint version used in CFEclipse?

Best,
Bernhard

**Comment by ryaneberly** [comment]
It sounds like a mismatch between the cfparser and clint versions.

**Comment by denuno** [comment]
That's exactly what this turned out to be, mismatched parser/linter versions.  I thought a failing test had prevented a build for the Eclipse plugin, but in the end I had to wipe out the Jenkins project to get a fresh build... happens every once in a while, should have tried that first.  At any rate, an Eclipse update should  now pull in the correct versions of stuff, sorry for the confusion.

**Comment by ryaneberly** [comment]
Thanks Denny


On June 10, 2017, at 10:24 PM, Denny Valliant <notifications@github.com> wrote:

Closed #292.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cflint/CFLint","title":"cflint/CFLint","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/cflint/CFLint">https://github.com/cflint/CFLint</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #292."}],"action":{"name":"View Issue","url":"<a href="https://github.com/cflint/CFLint/issues/292#event-1118403065">https://github.com/cflint/CFLint/issues/292#event-1118403065</a>"}}}
