### ISSUE TITLE
Suggestion : Un-document the -configfile parameter.  

### ISSUE THREAD

**Issue by ryaneberly** [cflint/CFLint#507]
I suggest we remove the configfile parameter from the help prompt and README.  It is not intended for the  average user.   .cflintrc is the preferred way to configure the tool.

I think @TheRealAgentK recommended this a while back as well.

**Comment by TheRealAgentK** [comment]
Yes, I'm still all for that. Anything that makes the configuration less complex will be good.

**Comment by TheRealAgentK** [comment]
Will change the documentation for it tomorrow.

**Comment by KamasamaK** [comment]
I was only using this parameter in my extension(s) to

1. Force the proper `.cflintrc` to be used because automated searching was not working with `-stdin` previously. This appears to be fixed.
2. Override or fallback on a given alternate configuration. I do not have any metrics on whether this is really being used by anyone.

**Comment by TheRealAgentK** [comment]
Done in ca12fd3ba790bf52ac3eed5bb93988df9de75dc0 (merged into dev)
