### ISSUE TITLE
Captialisation validation should be off by default as not a standard or best practice

### ISSUE THREAD

**Issue by dawesi** [cflint/CFLint#551]
Capitalisation of filenames by default sets an error if PascalCase is not used.

This is not a standard or best practice (never seen pascalcase used anywhere in cfml in 20 years of coding to be honest.

As this format is a preference and should be only set in configuration, not as default. this is a bug.

**Comment by KamasamaK** [comment]
That does not not trigger an Error; that issue is set to Info.

Regarding whether it's a standard or best practice, the conventions I see most often are borrowed from Java, which does use PascalCase for class names. For example, here is the Ortus standard -- [Class/Component/Interface Names](https://github.com/Ortus-Solutions/coding-standards/blob/master/coldfusion.md#classcomponentinterface-names).

Regarding configuration, you can ignore or configure the rules as you see fit using the `.cflintrc` file. See the [README](https://github.com/cflint/CFLint/blob/master/README.md) for how this can be done. Also, see the [RULES](https://github.com/cflint/CFLint/blob/master/RULES.md) for the names and defaults. The value you are referencing is `ComponentNameChecker.case`.

**Comment by dawesi** [comment]
I still think this info should be OFF by default, but configurable ON by config as it's not a cf standard. My 2c, but can use alt file for now.

Using through VS code... thanks for your work on this! #niceone

**Comment by KamasamaK** [comment]
I have no issue with an opt-in model, which has come up in other issues before, but I don't believe there is currently a mechanism in place to allow for this. 

To be clear on this rule in particular, you are correct that using a particular case anywhere is not an official CFML standard. However, having a naming convention and being consistent with it is a best practice, and that's what this rule enforces. PascalCase is simply the default for `ComponentNameChecker`, but it is easily changeable and I don't feel there is any harm in having all configurable rules with some default. CFLint is opinionated.
