### ISSUE TITLE
cflint-disable / cflint-enable ?

### ISSUE THREAD

**Issue by ghedwards** [cflint/CFLint#66]
Feature request:

It would be great to be able to disable CFLint rules in the code, something like the CF comment below 

&lt;!--- cflint-disable RULE ---&gt;
&lt;!--- cflint-enable RULE ---&gt;

A similar syntax is available in "eslint"

**Comment by ryaneberly** [comment]
I like the suggestion.  And it turns out the implementation for tags is pretty easy.

I implemented 
&lt;!--- cflint-disable RULE ---&gt;
or
&lt;!--- cflint-disable RULE,RULE ---&gt;
it is case insensitive.

Example:
&lt;cffunction&gt;
&lt;!--- CFLINT-DISABLE ARG_DEFAULT_MISSING---&gt;
&lt;cfargument name=\"xyz\"&gt;

This disables messages for the immediate following tag and all of it's children.
This functionality works for messages generated by something inside cfscript, just put the disable tag on the cfscript tag or one of it's parents..

I did not implement cflint-enable.

**Comment by ghedwards** [comment]
What about lines the CFLinter is not able to parse, could we get some sort of flag to disable parsing of the line? i.e.
						&lt;cfset generatedService.write(JavaCast("string","#temp.text##Chr(13)##Chr(10)#"))&gt; &lt;!--- cflint-disable-line ---&gt;

**Comment by ghedwards** [comment]
Also, should this work, because it's still reporting an error on not defining the new Query datatypes?

&lt;!--- cfline-disable TypedQueryNew ---&gt;
&lt;cfset st = QueryNew( JSONdecode(structVal) ) /&gt;

**Comment by ryaneberly** [comment]
I used the actual message codes, not the rule names.
